### ISSUE TITLE
How to action a JFrame close event, isn't clear from the documentation

### ISSUE THREAD

**Issue by paul-hammant** [jalian-systems/marathonv5#10]
https://www.google.com/search?q=windowClosing+site%3Ahttps%3A%2F%2Fmarathontesting.com

Any advice?

**Comment by kdmurthy** [comment]
You mean closing a window using the (X) close button right? The best is to use driver.execute_script to generate the event. Something like the following should work:

driver.executeScript("javax.swing.SwingUtilities.getWindowAncestor($1).dispose();", element);

*element* can be any component in the window.

**Comment by kdmurthy** [comment]
Scratch that...

driver.close() should close the current window.

**Comment by paul-hammant** [comment]
Cool

**Comment by paul-hammant** [comment]
You know, I opened the JFrame separately to starting Marathon via WebDriver. 

Marathon closing JFrame(s) would be incorrect IMO.  I think the `javax.swing.SwingUtilities.getWindowAncestor($1).dispose();` snipped would be correct.

**Comment by kdmurthy** [comment]
`driver.close()` supposed to close the currently opened browser window - I thought the corresponding operation in Marathon is to close the current window. That is also influenced by the need for marathon to record and operate window close operations. Since the decorations are handled by OS, can't really get handles to them.
